### ISSUE TITLE
I cannot run "Git clone git@github.com:techno-tim/techno-boto-discord.git)

### ISSUE THREAD

**Issue by MarcPKerr** [techno-tim/techno-boto-discord#1]
So when I run it it says this. Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Any way you can fix that?

**Comment by timothystewart6** [comment]
@MarcPKerr this isn't a problem with GitHub or this repo, it seems like you don't have git configured correctly.

See this video for how to set up `git` correctly as well as setting up your machine for JavaScript development.

https://www.youtube.com/watch?v=kL8iGErULiw
